{"uuid": "573828bf-838e-405a-a19b-4a232acf9f2f", "children": ["1b731a7e-6172-423b-b99e-6f6dd4c4a5df"], "befores": [{"name": "_xunit_setup_class_fixture_TestSupAdd", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=110.0.5481.178)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00B337D3]\n\t(No symbol) [0x00AC8B81]\n\t(No symbol) [0x009CB36D]\n\t(No symbol) [0x009C772D]\n\t(No symbol) [0x009BDC65]\n\t(No symbol) [0x009BF033]\n\t(No symbol) [0x009BDF02]\n\t(No symbol) [0x009BD324]\n\t(No symbol) [0x009BD241]\n\t(No symbol) [0x009BBC95]\n\t(No symbol) [0x009BC518]\n\t(No symbol) [0x009CCF4C]\n\t(No symbol) [0x00A31E01]\n\t(No symbol) [0x00A1B41C]\n\t(No symbol) [0x00A31215]\n\t(No symbol) [0x00A1B216]\n\t(No symbol) [0x009F0D97]\n\t(No symbol) [0x009F253D]\n\tGetHandleVerifier [0x00DAABF2+2510930]\n\tGetHandleVerifier [0x00DD8EC1+2700065]\n\tGetHandleVerifier [0x00DDC86C+2714828]\n\tGetHandleVerifier [0x00BE3480+645344]\n\t(No symbol) [0x00AD0FD2]\n\t(No symbol) [0x00AD6C68]\n\t(No symbol) [0x00AD6D4B]\n\t(No symbol) [0x00AE0D6B]\n\tBaseThreadInitThunk [0x779400F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77C47BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77C47B8E+238]\n\n", "trace": "  File \"D:\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\python.py\", line 854, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\python.py\", line 776, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\test_login\\shugu\\tcases\\sup\\test_sup_add.py\", line 20, in setup_class\n    self.plogin.open_url(pconst.const_url)\n  File \"D:\\test_login\\shugu\\pages\\login\\p_login.py\", line 31, in open_url\n    self.driver.open(url)\n  File \"D:\\test_login\\shugu\\common\\driver.py\", line 36, in open\n    self.driver.get(page_url)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1677632642161, "stop": 1677632658004}], "start": 1677632642161, "stop": 1677632658064}